"""added edits and edit_count to message table

Revision ID: 02d22087c3b1
Revises: 720be37d956c
Create Date: 2025-03-05 07:48:55.848164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02d22087c3b1'
down_revision = '720be37d956c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edits', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('edit_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('edit_count')
        batch_op.drop_column('edits')

    # ### end Alembic commands ###
