"""added edits and edit_count to message table

Revision ID: 368ece3eab9d
Revises: 54f66cd71d1d
Create Date: 2025-03-10 09:56:40.569511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '368ece3eab9d'
down_revision = '54f66cd71d1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edit_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('edits', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('edits')
        batch_op.drop_column('edit_count')

    # ### end Alembic commands ###
