"""added source and unique constraint to documents

Revision ID: 53ae9292ba02
Revises: 9d74b8e8d555
Create Date: 2025-01-14 08:28:51.150142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53ae9292ba02'
down_revision = '9d74b8e8d555'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=50), nullable=False))
        batch_op.create_unique_constraint('uq_document_id_source', ['id', 'source'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint('uq_document_id_source', type_='unique')
        batch_op.drop_column('source')

    # ### end Alembic commands ###
