"""added edits and edit_count to message table

Revision ID: 810fcde86fa1
Revises: 329c22bb734d
Create Date: 2025-03-06 10:43:33.085894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '810fcde86fa1'
down_revision = '329c22bb734d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('edits', sa.JSON(), nullable=True),
    sa.Column('edit_count', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
