"""added edits and edit_count to message table

Revision ID: 9a8f9be3e3c2
Revises: 02d22087c3b1
Create Date: 2025-03-06 09:31:46.117982

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9a8f9be3e3c2'
down_revision = '02d22087c3b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_edits', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('assistant_responses', sa.JSON(), nullable=True))
        batch_op.drop_column('edits')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edits', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.drop_column('assistant_responses')
        batch_op.drop_column('user_edits')

    # ### end Alembic commands ###
