"""Create tables

Revision ID: 9d74b8e8d555
Revises: 3f899345e3cb
Create Date: 2025-01-05 20:08:58.432035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d74b8e8d555'
down_revision = '3f899345e3cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        # batch_op.drop_index('content_tsv_idx', postgresql_using='gin')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('content_tsv_idx', [sa.text("to_tsvector('english'::regconfig, content)")], unique=False, postgresql_using='gin')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
