"""Create GeneralDocument table

Revision ID: c992882f69dd
Revises: ca8fec499e48
Create Date: 2025-02-24 20:44:40.179348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c992882f69dd'
down_revision = 'ca8fec499e48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('general_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=200), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('general_documents')
    # ### end Alembic commands ###
