"""added uploaded date to all document tables

Revision ID: caf76a726fe2
Revises: 368ece3eab9d
Create Date: 2025-03-11 16:29:46.260881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caf76a726fe2'
down_revision = '368ece3eab9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upload_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('business_operation_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upload_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('client_experience_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upload_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('communication_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upload_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('general_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upload_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('hr_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upload_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('internal_operation_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upload_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('it_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upload_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('legal_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upload_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('marketing_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upload_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('portfolio_risk_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upload_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('product_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upload_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('reconciliation_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upload_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('recovery_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upload_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('sales_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upload_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('transformation_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upload_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('underwriter_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upload_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('underwriter_documents', schema=None) as batch_op:
        batch_op.drop_column('upload_date')

    with op.batch_alter_table('transformation_documents', schema=None) as batch_op:
        batch_op.drop_column('upload_date')

    with op.batch_alter_table('sales_documents', schema=None) as batch_op:
        batch_op.drop_column('upload_date')

    with op.batch_alter_table('recovery_documents', schema=None) as batch_op:
        batch_op.drop_column('upload_date')

    with op.batch_alter_table('reconciliation_documents', schema=None) as batch_op:
        batch_op.drop_column('upload_date')

    with op.batch_alter_table('product_documents', schema=None) as batch_op:
        batch_op.drop_column('upload_date')

    with op.batch_alter_table('portfolio_risk_documents', schema=None) as batch_op:
        batch_op.drop_column('upload_date')

    with op.batch_alter_table('marketing_documents', schema=None) as batch_op:
        batch_op.drop_column('upload_date')

    with op.batch_alter_table('legal_documents', schema=None) as batch_op:
        batch_op.drop_column('upload_date')

    with op.batch_alter_table('it_documents', schema=None) as batch_op:
        batch_op.drop_column('upload_date')

    with op.batch_alter_table('internal_operation_documents', schema=None) as batch_op:
        batch_op.drop_column('upload_date')

    with op.batch_alter_table('hr_documents', schema=None) as batch_op:
        batch_op.drop_column('upload_date')

    with op.batch_alter_table('general_documents', schema=None) as batch_op:
        batch_op.drop_column('upload_date')

    with op.batch_alter_table('communication_documents', schema=None) as batch_op:
        batch_op.drop_column('upload_date')

    with op.batch_alter_table('client_experience_documents', schema=None) as batch_op:
        batch_op.drop_column('upload_date')

    with op.batch_alter_table('business_operation_documents', schema=None) as batch_op:
        batch_op.drop_column('upload_date')

    with op.batch_alter_table('account_documents', schema=None) as batch_op:
        batch_op.drop_column('upload_date')

    # ### end Alembic commands ###
